CREATE TABLE IF NOT EXISTS bs_watcha_book_meta (
    snowflake_id          VARCHAR(36)  NOT NULL PRIMARY KEY,
    created_at            DATETIME     NOT NULL,
    updated_at            DATETIME     NULL,
    book_code             VARCHAR(255) NULL,
    book_title            VARCHAR(255) NULL,
    book_subtitle         VARCHAR(255) NULL,
    book_index            MEDIUMTEXT   NULL,
    publish_year          INT          NULL,
    book_description      MEDIUMTEXT   NULL,
    publisher_description MEDIUMTEXT   NULL,
    author_description    MEDIUMTEXT   NULL,
    average_rating        DOUBLE       NULL,
    ratings_count         INT UNSIGNED NULL,
    wishes_count          INT UNSIGNED NULL,
    poster_hd             MEDIUMTEXT   NULL,
    poster_xlarge         MEDIUMTEXT   NULL,
    poster_large          MEDIUMTEXT   NULL,
    poster_medium         MEDIUMTEXT   NULL,
    poster_small          MEDIUMTEXT   NULL,
    authors               TEXT         NULL,
    nations               TEXT         NULL,
    genres                TEXT         NULL,
    aladin_url            TEXT         NULL,
    yes24_url             TEXT         NULL,
    kyobo_url             TEXT         NULL
) COLLATE = utf8mb4_bin;